### ISSUE TITLE
Dependence on the `source` configuration

### ISSUE THREAD

**Issue by anwa17** [tevio/jekyll-webpack#5]
I have the problem, that with this plugin you have to have the node infrastructure (mainly the `entrypoint`) inside of the jekyll source dir.

While it gives the opportunity to force jekyll watch over the possible changes, it also has the  drawbacks of copying the source file into the destination directory which in my opinion can not be the desired effect.

The solution to this would be:

1.  Let the user configure the source directory and __not__ chdir into the `source` dir as this plugin is currently doing.
2.  If the configured `entry` of webpack is inside of the configured `source` directory, then we could simply remove if afterwarts with an additional hook.

**Comment by tevio** [comment]
I have addressed this in the v0.2.3 release, you can now supply some options in `_config.yml` - please see the [README](https://github.com/tevio/jekyll-webpack/blob/master/README.md#cleanup)
